### PR TITLE
fix migrate command example

### PR DESCRIPTION
**Pull request by maxwells**
Just gave `amber db create migrate` a try. I believe it was meant to be `amber db migrate`.

### CODE REVIEW

**Comment by faustinoaq** [comment]
@maxwells Yeah, `amber db create migrate` fails with `sqlite3` then you should use `amber db migrate`

Postgres and MySQL should work with `amber db create migrate`

**Comment by faustinoaq** [comment]
A new warning message was introduced here 👉 https://github.com/amberframework/amber/pull/452

Currently (amber v0.6.4) `amber db create migrate` looks like:

```
➜  blog git:(master) ✗ amber db create migrate
03:16:03 Class      | (INFO) No migration files were found. For sqlite3, the database will be created during the first migration.
03:16:03 Database   | (INFO) #<IO::FileDescriptor:0x55f919859e10>
03:16:03 Database   | (INFO) Migrating db, current version: 0, target: 20180131134911565
03:16:03 Database   | (INFO) OK   20180131134911565_create_tasks.sql
```

So, I think we can keep `amber db create migrate` 😅

**Comment by faustinoaq** [comment]
Wait... I misread 😅 

@maxwells My bad, this is for amber-auth example, so yes, We should NOT use `amber db create` just `amber db migrate`

Thank you! 👍

**Comment by maxwells** [comment]
Thanks for taking a look! I've already closed my terminal so I can't remember why it failed for me (as a postgres user). I must have introduced some other confounding issue

**Pull request closed without merging**
